---
title: "R Notebook"
output: html_document
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
```{r}
# Set the directory and file name
# directory <- "/home/pedro/PycharmProjects/Streameco"
directory <- "C:/Users/pedro/OneDrive/Ambiente de Trabalho/Streameco"
setwd(directory)

file <- "total_reads.xlsx"
file2 <- "top10.xlsx"
file3 <- "menor_cutoff_reads.xlsx"
file4 <- "hyphomycetes_aquaticos.xlsx"
path <- file.path(directory, file)
path2 <- file.path(directory, file2)
path3 <- file.path(directory, file3)
path4 <- file.path(directory, file4)
```
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}
# Load the required packages
library(readxl)
library(mgcv)
library(ade4)
library(usdm)
library(vegan)
library(purrr)
library(ggplot2)
library(ggrepel)
library(factoextra)
library(xlsx)
library(abdiv)
library(dplyr)
```


```{r}
read_excel_sheets <- function(path, file){
  my_sheet_names <- excel_sheets(path)
  my_sheets <- lapply(my_sheet_names, function(x) read_excel(file, sheet = x))
  names(my_sheets) <- my_sheet_names
  return(my_sheets)
}

excel2dataframe <- function(x) {
  x <- as.data.frame(x)
  row.names(x) <- x[, 1]
  x <- x[, -1]
}

bact_fung_taxa <- lapply(read_excel_sheets(path, file), excel2dataframe)
```


```{r}
# Índice de Shannon
shannon_by_column <- function(data, name) {
  # Create an empty data frame to store the results
  shannon_df <- data.frame(shannon = numeric(), row.names = character(), stringsAsFactors = FALSE)
  for(i in 1:ncol(data)) {       # for-loop over columns
  shannon <- data.frame(shannon = diversity(t(data[,i]), index = "shannon", MARGIN = 1, base = exp(1)),
                         row.names = colnames(data)[i])
  # Add the current result to the shannon_df data frame
  shannon_df <- rbind(shannon_df, shannon)
  }
  # Name of dataframe
  name_col <- paste("shannon_index", sub("_([^_]*)$", "", name), sep="_")
  colnames(shannon_df)[1] <- name_col
  return(shannon_df)
}


shannon <- lapply(names(bact_fung_taxa), function(df_name) {
  shannon_by_column(bact_fung_taxa[[df_name]], df_name)
})

# Índice de Pielou
pielou_by_column <- function(data, name) {
  # Create an empty data frame to store the results
  pielou_df <- data.frame(pielou = numeric(), row.names = character(), stringsAsFactors = FALSE)
  for(i in 1:ncol(data)) {       # for-loop over columns
  pielou <- data.frame(pielou = diversity(t(data[,i]))/log(specnumber(t(data[,i]))),
                         row.names = colnames(data)[i])
  # Add the current result to the shannon_df data frame
  pielou_df <- rbind(pielou_df, pielou)
  }
  # Name of dataframe
  name_col <- paste("pielou_index", sub("_([^_]*)$", "", name), sep="_")
  colnames(pielou_df)[1] <- name_col
  return(pielou_df)
}

pielou <- lapply(names(bact_fung_taxa), function(df_name) {
  pielou_by_column(bact_fung_taxa[[df_name]], df_name)
})

# Bray-Curtis
bray <- lapply(bact_fung_taxa, function(x) vegdist(t(x)))

# Jaccard
jaccard <- lapply(bact_fung_taxa, function (x) vegdist(t(x), method = "jaccard"))

# Margalef
margalef_by_column <- function(data, name) {
  # Create an empty data frame to store the results
  margalef_df <- data.frame(margalef = numeric(), row.names = character(), stringsAsFactors = FALSE)
  for(i in 1:ncol(data)) {       # for-loop over columns
  margalef <- data.frame(margalef = margalef(data[, i]),
                         row.names = colnames(data)[i])
  # Add the current result to the shannon_df data frame
  margalef_df <- rbind(margalef_df, margalef)
  }
  # Name of dataframe
  name_col <- paste("margalef_index", sub("_([^_]*)$", "", name), sep="_")
  colnames(margalef_df)[1] <- name_col
  return(margalef_df)
}

margalef_ind <- lapply(names(bact_fung_taxa), function(df_name) {
  margalef_by_column(bact_fung_taxa[[df_name]], df_name)
})

# Simpson
simpson_by_column <- function(data, name) {
  # Create an empty data frame to store the results
  simpson_df <- data.frame(simpson = numeric(), row.names = character(), stringsAsFactors = FALSE)
  for(i in 1:ncol(data)) {       # for-loop over columns
  simpson <- data.frame(simpson = diversity(t(data[,i]), index = "simpson", MARGIN = 1, base = exp(1)),
                         row.names = colnames(data)[i])
  # Add the current result to the shannon_df data frame
  simpson_df <- rbind(simpson_df, simpson)
  }
  # Name of dataframe
  name_col <- paste("simpson_index", sub("_([^_]*)$", "", name), sep="_")
  colnames(simpson_df)[1] <- name_col
  return(simpson_df)
}


simpson_ind <- lapply(names(bact_fung_taxa), function(df_name) {
  simpson_by_column(bact_fung_taxa[[df_name]], df_name)
})

# Guardar excel dos índices
wb <- createWorkbook()

sheet <- createSheet(wb, "shannon")

addDataFrame(Reduce(merge, lapply(shannon, function(x) data.frame(x, site = row.names(x)))), sheet=sheet,
             startColumn=1, row.names=FALSE)

sheet <- createSheet(wb, "pielou")

addDataFrame(Reduce(merge, lapply(pielou, function(x) data.frame(x, site = row.names(x)))), sheet=sheet,
             startColumn=1, row.names=FALSE)

sheet <- createSheet(wb, "margalef")

addDataFrame(Reduce(merge, lapply(margalef_ind, function(x) data.frame(x, site = row.names(x)))), sheet=sheet,
             startColumn=1, row.names=FALSE)

sheet <- createSheet(wb, "simpson")

addDataFrame(Reduce(merge, lapply(simpson_ind, function(x) data.frame(x, site = row.names(x)))), sheet=sheet,
             startColumn=1, row.names=FALSE)

saveWorkbook(wb, "bioindices.xlsx")
```


```{r}
# Variáveis ambientais
env.data <- read.table("var ambientais.txt", sep="\t", dec=".", header=T)
row.names(env.data) <- env.data$code
env.data <- env.data[, -1]
env.data <- as.data.frame(env.data)
env.data2 <- env.data[, c(12, 23, 24, 25, 27, 28, 32, 37)]
env_data <- env.data[, -c(12, 23, 24, 25, 27, 28, 32, 37)]
row.names(env.data2) <- row.names(env_data)
# Apenas para hyphomycetes
# env.data <- env.data[-40,]
```



```{r}
shannon_index <- lapply(bact_fung_taxa, function(x) diversity(t(x), index = "shannon", base = exp(1)))

pielou_index <- lapply(bact_fung_taxa, function (x) diversity(t(x))/log(specnumber(t(x))))

margalef_index <- lapply(bact_fung_taxa, function (x) apply(x, 2, margalef))


simpson_index <- lapply(bact_fung_taxa, function (x) diversity(t(x), index = "simpson", MARGIN = 1, base = exp(1)))

PCA_env <- rep(list(prcomp(env_data, scale = FALSE)), times = 12)
PCA_dataframe <- map2(shannon_index, PCA_env, function(ind, env) {
  data.frame(bioindex = ind, environmental_data = env$x[,1])
})


all_graphs <- map2(PCA_env, PCA_dataframe, function (pca_env, all_dataframe){
  fviz_eig(pca_env)

  fviz_pca_ind(pca_env,
               col.ind = "cos2", # Color by the quality of representation
               gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
               repel = TRUE     # Avoid text overlapping
  )

  fviz_pca_var(pca_env,
               col.var = "contrib", # Color by contributions to the PC
               gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
               repel = TRUE     # Avoid text overlapping
  )

  ggplot(all_dataframe, aes(x=environmental_data, y=bioindex)) +
    geom_point() +
    geom_text(aes(label = rownames(all_dataframe)), size = 2.5, nudge_x = 1, nudge_y = 1.2) +
    labs(x="Environmental variables", y="Aquatic Hyphomycetes") +
    theme(legend.position = "none")
})

pdf("PCA_all.pdf")
for (i in 1:length(all_graphs)) {
  print(all_graphs[[i]])
}
dev.off()

```
